package Token;


//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 29 14:11:47 CST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS_MINUS = 52;
  public static final int AT = 75;
  public static final int SHORT = 13;
  public static final int SIGNED = 30;
  public static final int IDENTIFIER = 79;
  public static final int GT = 77;
  public static final int POINTER = 66;
  public static final int READ = 21;
  public static final int PLUS_EQ = 53;
  public static final int NOTEQ = 73;
  public static final int TOS = 59;
  public static final int LT_LT = 58;
  public static final int REGISTER = 29;
  public static final int ENUM = 26;
  public static final int RBRACK = 39;
  public static final int SIZEOF = 31;
  public static final int COMMA = 41;
  public static final int RBRACE = 37;
  public static final int GT_GT_EQ = 65;
  public static final int RPAREN = 68;
  public static final int LBRACK = 38;
  public static final int LT = 78;
  public static final int ANDAND = 74;
  public static final int OROR = 76;
  public static final int STRUCT = 32;
  public static final int LBRACE = 36;
  public static final int MOD_EQ = 60;
  public static final int LPAREN = 67;
  public static final int INTEGER_LITERAL = 80;
  public static final int NOT = 43;
  public static final int FLOAT = 11;
  public static final int GOTO = 28;
  public static final int PLUS_PLUS = 51;
  public static final int AT_EQ = 61;
  public static final int EQ = 69;
  public static final int BOOLEAN_LITERAL = 82;
  public static final int MOD = 50;
  public static final int WRITE = 22;
  public static final int UP_EQ = 62;
  public static final int LONG = 12;
  public static final int PLUS = 46;
  public static final int QUESTION = 44;
  public static final int WHILE = 10;
  public static final int CHAR = 3;
  public static final int BOOLEAN = 2;
  public static final int SWITCH = 20;
  public static final int DO = 18;
  public static final int FOR = 19;
  public static final int VOID = 9;
  public static final int EXTERN = 27;
  public static final int DIV = 49;
  public static final int DIV_EQ = 56;
  public static final int PUBLIC = 7;
  public static final int RETURN = 8;
  public static final int MULT = 48;
  public static final int ELSE = 4;
  public static final int GTEQ = 72;
  public static final int BREAK = 14;
  public static final int LT_LT_EQ = 64;
  public static final int DOT = 42;
  public static final int INT = 5;
  public static final int NULL_LITERAL = 87;
  public static final int OCT_LITERAL = 86;
  public static final int STRING_LITERAL = 84;
  public static final int EQEQ = 70;
  public static final int EOF = 0;
  public static final int SEMICOLON = 40;
  public static final int OR_EQ = 63;
  public static final int DEFAULT = 17;
  public static final int MINUS_EQ = 54;
  public static final int MINUS = 47;
  public static final int LTEQ = 71;
  public static final int ERROR = 1;
  public static final int CONTINUE = 16;
  public static final int IF = 6;
  public static final int UNSIGNED = 23;
  public static final int COLON = 45;
  public static final int HEX_LITERAL = 85;
  public static final int CHARACTER_LITERAL = 83;
  public static final int MULT_EQ = 55;
  public static final int GT_GT = 57;
  public static final int VOLATILE = 34;
  public static final int CASE = 15;
  public static final int STATIC = 25;
  public static final int TYPEDEF = 33;
  public static final int AUTO = 24;
  public static final int FLOATING_POINT_LITERAL = 81;
  public static final int UP = 93;
  public static final int CONST = 35;
}

