/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Token;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 25 07:53:36 CST 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 49;
  public static final int GTEQ = 38;
  public static final int MULT = 10;
  public static final int CHAR = 4;
  public static final int LTEQ = 37;
  public static final int LPAREN = 15;
  public static final int INT = 3;
  public static final int MINUS = 31;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 47;
  public static final int OROR = 42;
  public static final int CHARACTER_LITERAL = 48;
  public static final int NOT = 32;
  public static final int SEMICOLON = 9;
  public static final int LT = 35;
  public static final int ILLEGAL_CHARACTER = 44;
  public static final int COMMA = 11;
  public static final int CLASS = 19;
  public static final int ANDAND = 41;
  public static final int DIV = 33;
  public static final int PLUS = 30;
  public static final int NULL_LITERAL = 51;
  public static final int IF = 25;
  public static final int THIS = 22;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 28;
  public static final int SUPER = 23;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int EQEQ = 39;
  public static final int MOD = 34;
  public static final int VOID = 21;
  public static final int EQ = 14;
  public static final int LBRACK = 6;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 46;
  public static final int LBRACE = 12;
  public static final int ELSE = 26;
  public static final int RBRACK = 7;
  public static final int WHILE = 27;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 20;
  public static final int QUESTION = 43;
  public static final int AT = 24;
  public static final int GT = 36;
  public static final int NOTEQ = 40;
  public static final int IDENTIFIER = 50;
  public static final int INTEGER_LITERAL = 45;
  
  // AGREGADO
    //OPS
  public static final int PLUS_PLUS = 52;
  public static final int MINUS_MINUS = 53;
  public static final int PLUS_EQ = 54;
  public static final int MINUS_EQ = 55;
  public static final int MULT_EQ = 56;
  public static final int DIV_EQ = 57;
  
  public static final int HEX_LITERAL = 58;
  public static final int OCT_LITERAL = 59;
  
  public static final int LONG = 60;
  public static final int SHORT = 61;
  
  
  public static final int BREAK = 62;
  public static final int CASE = 63;
  public static final int CONTINUE = 64;
  public static final int DEFAULT = 65;
  public static final int DO = 66;
  public static final int FOR = 67;
  public static final int SWITCH = 68;
  public static final int READ = 69;
  public static final int WRITE = 70;
  public static final int ETIQUETA = 71;
  public static final int CONST = 72;

  public static final int UNSIGNED = 73;
  public static final int AUTO = 74;
  public static final int STATIC = 75;
  public static final int ENUM = 76;
  public static final int EXTERN = 77;
  public static final int GOTO = 78;
  public static final int REGISTER = 79;
  public static final int SIGNED = 80;
  public static final int SIZEOF = 81;
  public static final int STRUCT = 82;
  public static final int TYPEDEF = 83;
  public static final int VOLATILE= 84;
  public static final int MAIN= 85;
  
  public static final int UP = 86;
  public static final int GT_GT = 87;
  public static final int LT_LT = 88;
  public static final int TOS = 89;
  public static final int MOD_EQ = 90;
  public static final int AT_EQ = 91;
  public static final int UP_EQ = 92;
  public static final int OR_EQ = 93;
  public static final int LT_LT_EQ = 94;
  public static final int GT_GT_EQ = 95;
  public static final int POINTER = 96;
  
  public static final int ERROR = 97;
  
          
   
}


