/* The following code was generated by JFlex 1.4.3 on 5/23/14 12:12 AM */



package analizador_lexico;
import java_cup.runtime.*;
import Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/23/14 12:12 AM from the specification file
 * <tt>src/analizador_lexico/Lexer.flex</tt>
 */
public class Scanner implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\65"+
    "\1\22\1\25\1\6\1\73\1\70\1\23\1\52\1\53\1\5\1\72"+
    "\1\61\1\14\1\12\1\4\1\10\10\15\1\11\1\67\1\60\1\64"+
    "\1\62\1\63\1\66\1\0\4\20\1\13\1\20\24\6\1\56\1\24"+
    "\1\57\1\0\1\6\1\0\1\32\1\26\1\34\1\46\1\31\1\42"+
    "\1\50\1\35\1\40\1\6\1\51\1\30\1\6\1\33\1\27\1\43"+
    "\1\6\1\36\1\37\1\41\1\44\1\45\1\47\1\21\2\6\1\54"+
    "\1\71\1\55\1\0\41\7\2\0\4\6\4\0\1\6\2\0\1\7"+
    "\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6\1\0\u01ca\6"+
    "\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6\21\0\160\7"+
    "\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0\3\6\1\0"+
    "\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0\5\7\2\0"+
    "\236\6\11\0\46\6\2\0\1\6\7\0\47\6\11\0\55\7\1\0"+
    "\1\7\1\0\2\7\1\0\2\7\1\0\1\7\10\0\33\6\5\0"+
    "\3\6\15\0\4\7\7\0\1\6\4\0\13\7\5\0\53\6\37\7"+
    "\4\0\2\6\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6"+
    "\2\7\1\0\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7"+
    "\1\6\1\7\36\6\33\7\2\0\131\6\13\7\1\6\16\0\12\7"+
    "\41\6\11\7\2\6\4\0\1\6\5\0\26\6\4\7\1\6\11\7"+
    "\1\6\3\7\1\6\5\7\22\0\31\6\3\7\244\0\4\7\66\6"+
    "\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7\1\0"+
    "\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0\3\7"+
    "\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7"+
    "\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0\14\7"+
    "\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\10\7"+
    "\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7\2\0"+
    "\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6\1\0"+
    "\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7\3\0"+
    "\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7\11\0"+
    "\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7\22\0"+
    "\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0\2\6"+
    "\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0\2\6"+
    "\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0"+
    "\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7"+
    "\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0"+
    "\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0"+
    "\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0"+
    "\1\6\1\0\6\7\2\0\12\7\2\0\2\6\42\0\1\6\27\0"+
    "\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6\13\7"+
    "\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7\6\0"+
    "\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6\4\7"+
    "\15\6\14\7\1\6\17\7\2\0\46\6\12\0\53\6\1\0\1\6"+
    "\3\0\u0149\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6"+
    "\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6\2\0\7\6"+
    "\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6\1\0\4\6"+
    "\2\0\103\6\2\0\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6"+
    "\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6\17\0\15\6"+
    "\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6\2\7\14\0"+
    "\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7\3\0\1\6"+
    "\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0\12\7\6\0"+
    "\130\6\10\0\51\6\1\7\1\6\5\0\106\6\12\0\35\6\3\0"+
    "\14\7\4\0\14\7\12\0\12\7\36\6\2\0\5\6\13\0\54\6"+
    "\4\0\21\7\7\6\2\7\6\0\12\7\46\0\27\6\5\7\4\0"+
    "\65\6\12\7\1\0\35\7\2\0\13\7\6\0\12\7\15\0\1\6"+
    "\130\0\5\7\57\6\21\7\7\6\4\0\12\7\21\0\11\7\14\0"+
    "\3\7\36\6\12\7\3\0\2\6\12\7\6\0\46\6\16\7\14\0"+
    "\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0\3\7"+
    "\1\0\25\7\4\6\1\7\4\6\1\7\15\0\300\6\47\7\25\0"+
    "\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6"+
    "\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6"+
    "\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6"+
    "\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0\5\7"+
    "\15\0\1\16\14\0\5\7\4\0\1\17\13\0\2\6\23\0\1\6"+
    "\13\0\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0\15\6"+
    "\3\0\32\6\26\0\15\7\4\0\1\7\3\0\14\7\21\0\1\6"+
    "\4\0\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6"+
    "\5\0\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6"+
    "\1\0\205\6\6\0\4\6\3\7\16\0\46\6\12\0\66\6\11\0"+
    "\1\6\17\0\1\7\27\6\11\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7\1\0"+
    "\5\6\2\0\5\6\4\0\126\6\2\0\2\7\2\0\3\6\1\0"+
    "\132\6\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0"+
    "\20\6\u0200\0\u19b6\6\112\0\u51cc\6\64\0\u048d\6\103\0\56\6\2\0"+
    "\u010d\6\3\0\20\6\12\7\2\6\24\0\57\6\1\7\14\0\2\7"+
    "\1\0\31\6\10\0\120\6\2\7\45\0\11\6\2\0\147\6\2\0"+
    "\4\6\1\0\2\6\16\0\12\6\120\0\10\6\1\7\3\6\1\7"+
    "\4\6\1\7\27\6\5\7\20\0\1\6\7\0\64\6\14\0\2\7"+
    "\62\6\21\7\13\0\12\7\6\0\22\7\6\6\3\0\1\6\4\0"+
    "\12\7\34\6\10\7\2\0\27\6\15\7\14\0\35\6\3\0\4\7"+
    "\57\6\16\7\16\0\1\6\12\7\46\0\51\6\16\7\11\0\3\6"+
    "\1\7\10\6\2\7\2\0\12\7\6\0\27\6\3\0\1\6\1\7"+
    "\4\0\60\6\1\7\1\6\3\7\2\6\2\7\5\6\2\7\1\6"+
    "\1\7\1\6\30\0\3\6\43\0\6\6\2\0\6\6\2\0\6\6"+
    "\11\0\7\6\1\0\7\6\221\0\43\6\10\7\1\0\2\7\2\0"+
    "\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u012e\6\2\0"+
    "\76\6\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\7"+
    "\12\6\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0"+
    "\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0"+
    "\15\6\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6\31\0"+
    "\1\6\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6\13\0"+
    "\12\7\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0"+
    "\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0"+
    "\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\1\1\11\1\12\1\1\16\5\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\1\1\32\1\33"+
    "\1\34\2\35\1\36\2\1\2\37\1\1\1\2\1\0"+
    "\1\40\1\41\2\42\1\0\1\43\1\44\2\0\2\45"+
    "\14\5\1\46\6\5\1\47\3\5\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\70\1\71\11\0"+
    "\1\42\3\0\14\5\1\72\1\5\1\73\7\5\1\74"+
    "\1\75\1\76\1\77\1\100\1\101\1\102\1\103\1\104"+
    "\1\0\2\5\1\105\1\106\1\107\2\5\1\110\1\111"+
    "\1\112\3\5\1\113\3\5\1\114\3\5\1\115\1\5"+
    "\1\116\1\117\2\5\1\120\1\5\1\121\1\122\2\5"+
    "\1\123\1\124\2\5\1\125\1\126\1\127\1\5\1\130"+
    "\1\5\1\131\1\132";

  private static int [] zzUnpackAction() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\264\0\u012c\0\u0168"+
    "\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\264\0\264"+
    "\0\u030c\0\u0348\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0"+
    "\0\u04ec\0\u0528\0\u0564\0\u05a0\0\u05dc\0\u0618\0\u0654\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\u0690"+
    "\0\u06cc\0\u0708\0\u0744\0\264\0\264\0\u0780\0\u07bc\0\u07f8"+
    "\0\264\0\u0834\0\u0870\0\264\0\264\0\u08ac\0\u08e8\0\u0924"+
    "\0\264\0\u0960\0\u099c\0\u09d8\0\264\0\264\0\u01e0\0\u0a14"+
    "\0\u0a50\0\264\0\264\0\u0a8c\0\u030c\0\u0ac8\0\264\0\u0b04"+
    "\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4"+
    "\0\u0d20\0\u0d5c\0\u0d98\0\u01a4\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88"+
    "\0\u0ec4\0\u0f00\0\u01a4\0\u0f3c\0\u0f78\0\u0fb4\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\u0ff0\0\u102c\0\u1068\0\u10a4\0\u10e0\0\u111c\0\u1158\0\u1194"+
    "\0\u11d0\0\u120c\0\u120c\0\u1248\0\u1284\0\u12c0\0\u12fc\0\u1338"+
    "\0\u1374\0\u13b0\0\u13ec\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u1518"+
    "\0\u1554\0\u01a4\0\u1590\0\u01a4\0\u15cc\0\u1608\0\u1644\0\u1680"+
    "\0\u16bc\0\u16f8\0\u1734\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\u1248\0\u1770\0\u17ac\0\u17e8\0\u01a4"+
    "\0\u01a4\0\u01a4\0\u1824\0\u1860\0\u01a4\0\u01a4\0\u01a4\0\u189c"+
    "\0\u18d8\0\u1914\0\u01a4\0\u1950\0\u198c\0\u19c8\0\u01a4\0\u1a04"+
    "\0\u1a40\0\u1a7c\0\u1770\0\u1ab8\0\u01a4\0\u01a4\0\u1af4\0\u1b30"+
    "\0\u01a4\0\u1b6c\0\u01a4\0\u01a4\0\u1ba8\0\u1be4\0\u01a4\0\u01a4"+
    "\0\u1c20\0\u1c5c\0\u01a4\0\u01a4\0\u01a4\0\u1c98\0\u01a4\0\u1cd4"+
    "\0\u01a4\0\u01a4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\1\14\1\11\1\15\1\13\1\16\1\4\2\11"+
    "\1\17\1\20\1\4\1\21\1\22\1\11\1\23\1\24"+
    "\1\11\1\25\1\26\1\11\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\11\1\35\1\36\1\37\2\11\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\17\62\1\65\1\62\1\66"+
    "\47\62\1\67\1\70\1\71\20\67\1\4\1\72\47\67"+
    "\76\0\1\6\75\0\1\73\1\74\54\0\1\75\73\0"+
    "\1\76\17\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\24\11\32\0\2\77\1\100\1\101\1\0"+
    "\1\77\13\0\1\101\52\0\2\13\1\100\1\101\1\0"+
    "\1\13\13\0\1\101\52\0\2\100\3\0\1\100\72\0"+
    "\1\102\45\0\1\103\21\0\1\104\63\0\1\105\1\106"+
    "\1\107\71\105\6\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\1\11\1\110\6\11\1\111\13\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\1\11\1\112\22\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\2\11\1\113\21\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\16\11\1\114\5\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\1\11\1\115\2\11"+
    "\1\116\2\11\1\117\14\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\3\11\1\120\20\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\7\11\1\121\11\11\1\122\2\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\5\11"+
    "\1\123\6\11\1\124\7\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\10\11\1\125\13\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\1\11\1\126\1\127\1\11\1\130\17\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\16\11\1\131\5\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\1\11\1\132\22\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\1\11\1\133\1\11\1\134\20\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\7\11\1\135"+
    "\1\136\13\11\104\0\1\137\73\0\1\140\73\0\1\141"+
    "\73\0\1\142\101\0\1\143\74\0\1\144\64\0\1\145"+
    "\7\0\1\146\1\0\1\62\2\0\17\62\1\0\1\62"+
    "\1\0\47\62\2\0\1\64\71\0\2\147\1\0\17\147"+
    "\1\150\1\151\1\152\1\147\1\153\4\147\1\154\2\147"+
    "\1\155\2\147\1\156\1\157\31\147\23\0\1\160\52\0"+
    "\1\71\113\0\1\161\1\162\1\163\1\0\1\164\4\0"+
    "\1\165\2\0\1\166\2\0\1\167\1\170\31\0\1\73"+
    "\1\5\1\6\71\73\5\74\1\171\66\74\10\0\2\100"+
    "\1\0\1\101\1\0\1\100\13\0\1\101\52\0\2\172"+
    "\2\0\1\173\1\172\54\0\1\173\20\0\1\174\1\0"+
    "\1\175\54\0\1\107\77\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\1\11\1\176\22\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\3\11\1\177\20\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\5\11\1\200\16\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\11\11\1\201\12\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\2\11\1\202\21\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\5\11\1\203\16\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\11\11\1\204\12\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\4\11\1\205\17\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\4\11\1\206\6\11\1\207"+
    "\10\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\1\11\1\210\22\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\12\11\1\211"+
    "\11\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\13\11\1\212\10\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\16\11\1\213"+
    "\5\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\10\11\1\214\13\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\1\11\1\215"+
    "\22\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\2\11\1\216\21\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\1\217\23\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\12\11\1\220\11\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\14\11\1\221\7\11"+
    "\30\0\4\11\1\0\1\11\1\0\1\11\2\0\2\11"+
    "\4\0\12\11\1\222\11\11\30\0\4\11\1\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\12\11\1\223\11\11"+
    "\45\0\1\224\73\0\1\225\73\0\1\226\73\0\1\227"+
    "\73\0\1\230\73\0\1\231\73\0\1\232\73\0\1\233"+
    "\50\0\4\74\1\6\1\171\66\74\10\0\2\172\3\0"+
    "\1\172\66\0\1\234\4\0\1\234\74\0\1\235\63\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\2\11\1\236\21\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\4\11\1\237\17\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\22\11\1\240\1\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\3\11\1\241\20\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\2\11\1\242\21\11\30\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\11\11\1\243\1\11\1\244"+
    "\10\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\3\11\1\245\20\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\10\11\1\246"+
    "\13\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\20\11\1\247\3\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\16\11\1\250"+
    "\5\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\10\11\1\251\13\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\13\11\1\252"+
    "\10\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\3\11\1\253\20\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\4\11\1\254"+
    "\17\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\11\11\1\255\12\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\2\11\1\256"+
    "\21\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\20\11\1\257\3\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\4\11\1\260"+
    "\17\11\30\0\4\11\1\0\1\11\1\0\1\11\2\0"+
    "\2\11\4\0\2\11\1\261\21\11\30\0\4\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\11\4\0\13\11\1\262"+
    "\10\11\32\0\2\263\1\0\1\263\1\0\1\263\2\0"+
    "\1\263\5\0\1\263\2\0\2\263\1\0\1\263\5\0"+
    "\1\263\3\0\1\263\33\0\4\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\4\0\3\11\1\264\20\11\30\0"+
    "\4\11\1\0\1\11\1\0\1\11\2\0\2\11\4\0"+
    "\23\11\1\265\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\13\11\1\266\10\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\12\11"+
    "\1\267\11\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\10\11\1\270\13\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\13\11"+
    "\1\271\10\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\6\11\1\272\15\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\13\11"+
    "\1\273\10\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\3\11\1\274\20\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\12\11"+
    "\1\275\11\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\16\11\1\276\5\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\3\11"+
    "\1\277\20\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\3\11\1\300\20\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\4\11"+
    "\1\301\17\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\5\11\1\302\16\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\5\11"+
    "\1\303\16\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\7\11\1\304\14\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\6\11"+
    "\1\305\15\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\2\11\1\306\21\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\5\11"+
    "\1\307\16\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\16\11\1\310\5\11\30\0\4\11"+
    "\1\0\1\11\1\0\1\11\2\0\2\11\4\0\13\11"+
    "\1\311\10\11\30\0\4\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\4\0\3\11\1\312\20\11\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7440];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\10\1\2\11\17\1\10\11"+
    "\4\1\2\11\3\1\1\11\2\1\2\11\3\1\1\11"+
    "\2\1\1\0\2\11\2\1\1\0\2\11\2\0\1\1"+
    "\1\11\27\1\22\11\11\0\1\1\3\0\26\1\10\11"+
    "\1\1\1\0\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[202];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, yytext());
  }

  private Symbol symbol(int type, Object value) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, yytext(), value);
  }

  public String current_lexeme(){
    int l = yyline+1;
    int c = yycolumn+1;
    return " (line: "+l+" , column: "+c+" , lexeme: '"+yytext()+"')";
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2228) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { return symbol(GTEQ);
          }
        case 91: break;
        case 36: 
          { return symbol(MINUS_EQ);
          }
        case 92: break;
        case 20: 
          { return symbol(GT);
          }
        case 93: break;
        case 43: 
          { return symbol(NOTEQ);
          }
        case 94: break;
        case 9: 
          { yybegin(STRING); string.setLength(0);
          }
        case 95: break;
        case 13: 
          { return symbol(LBRACE);
          }
        case 96: break;
        case 19: 
          { return symbol(EQ);
          }
        case 97: break;
        case 90: 
          { return symbol(CONTINUE);
          }
        case 98: break;
        case 39: 
          { return symbol(DO);
          }
        case 99: break;
        case 33: 
          { return symbol(MULT_EQ);
          }
        case 100: break;
        case 21: 
          { return symbol(LT);
          }
        case 101: break;
        case 55: 
          { string.append( '\t' );
          }
        case 102: break;
        case 87: 
          { return symbol(PUBLIC);
          }
        case 103: break;
        case 66: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\t'));
          }
        case 104: break;
        case 88: 
          { return symbol(BOOLEAN);
          }
        case 105: break;
        case 80: 
          { return symbol(SHORT);
          }
        case 106: break;
        case 10: 
          { yybegin(CHARLITERAL);
          }
        case 107: break;
        case 40: 
          { return symbol(EQEQ);
          }
        case 108: break;
        case 75: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 109: break;
        case 69: 
          { return symbol(LONG);
          }
        case 110: break;
        case 26: 
          { return symbol(PLUS);
          }
        case 111: break;
        case 53: 
          { string.append( '\n' );
          }
        case 112: break;
        case 68: 
          { return symbol(OCT_LITERAL, new Integer(yytext()));
          }
        case 113: break;
        case 12: 
          { return symbol(RPAREN);
          }
        case 114: break;
        case 79: 
          { return symbol(CONST);
          }
        case 115: break;
        case 77: 
          { return symbol(HEX_LITERAL, new Integer(yytext()));
          }
        case 116: break;
        case 64: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\n'));
          }
        case 117: break;
        case 37: 
          { return symbol(ETIQUETA);
          }
        case 118: break;
        case 59: 
          { return symbol(FOR);
          }
        case 119: break;
        case 34: 
          { return symbol(FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength())));
          }
        case 120: break;
        case 89: 
          { return symbol(DEFAULT);
          }
        case 121: break;
        case 23: 
          { return symbol(QUESTION);
          }
        case 122: break;
        case 3: 
          { return symbol(DIV);
          }
        case 123: break;
        case 73: 
          { return symbol(CHAR);
          }
        case 124: break;
        case 38: 
          { return symbol(IF);
          }
        case 125: break;
        case 5: 
          { return symbol(IDENTIFIER, yytext());
          }
        case 126: break;
        case 48: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 127: break;
        case 86: 
          { return symbol(SWITCH);
          }
        case 128: break;
        case 27: 
          { return symbol(MOD);
          }
        case 129: break;
        case 46: 
          { return symbol(PLUS_EQ);
          }
        case 130: break;
        case 11: 
          { return symbol(LPAREN);
          }
        case 131: break;
        case 54: 
          { string.append( '\r' );
          }
        case 132: break;
        case 78: 
          { return symbol(BREAK);
          }
        case 133: break;
        case 71: 
          { return symbol(NULL_LITERAL);
          }
        case 134: break;
        case 52: 
          { string.append( '\b' );
          }
        case 135: break;
        case 65: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\r'));
          }
        case 136: break;
        case 63: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\b'));
          }
        case 137: break;
        case 35: 
          { return symbol(MINUS_MINUS);
          }
        case 138: break;
        case 29: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 139: break;
        case 49: 
          { string.append( '\"' );
          }
        case 140: break;
        case 16: 
          { return symbol(RBRACK);
          }
        case 141: break;
        case 17: 
          { return symbol(SEMICOLON);
          }
        case 142: break;
        case 6: 
          { return symbol(INTEGER_LITERAL, new Integer(yytext()));
          }
        case 143: break;
        case 60: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\"'));
          }
        case 144: break;
        case 50: 
          { string.append( '\'' );
          }
        case 145: break;
        case 81: 
          { return symbol(FLOAT);
          }
        case 146: break;
        case 51: 
          { string.append( '\\' );
          }
        case 147: break;
        case 84: 
          { return symbol(WRITE);
          }
        case 148: break;
        case 72: 
          { return symbol(CASE);
          }
        case 149: break;
        case 8: 
          { return symbol(MINUS);
          }
        case 150: break;
        case 61: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\''));
          }
        case 151: break;
        case 7: 
          { return symbol(DOT);
          }
        case 152: break;
        case 47: 
          { return symbol(PLUS_PLUS);
          }
        case 153: break;
        case 62: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\\'));
          }
        case 154: break;
        case 58: 
          { return symbol(INT);
          }
        case 155: break;
        case 32: 
          { return symbol(DIV_EQ);
          }
        case 156: break;
        case 1: 
          { return symbol(ILLEGAL_CHARACTER, yytext());
          }
        case 157: break;
        case 24: 
          { return symbol(COLON);
          }
        case 158: break;
        case 42: 
          { return symbol(LTEQ);
          }
        case 159: break;
        case 56: 
          { string.append( '\f' );
          }
        case 160: break;
        case 76: 
          { return symbol(VOID);
          }
        case 161: break;
        case 22: 
          { return symbol(NOT);
          }
        case 162: break;
        case 30: 
          { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
          }
        case 163: break;
        case 14: 
          { return symbol(RBRACE);
          }
        case 164: break;
        case 67: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\f'));
          }
        case 165: break;
        case 4: 
          { return symbol(MULT);
          }
        case 166: break;
        case 2: 
          { /* ignore */
          }
        case 167: break;
        case 25: 
          { return symbol(AT);
          }
        case 168: break;
        case 74: 
          { return symbol(READ);
          }
        case 169: break;
        case 15: 
          { return symbol(LBRACK);
          }
        case 170: break;
        case 45: 
          { return symbol(OROR);
          }
        case 171: break;
        case 28: 
          { string.append( yytext() );
          }
        case 172: break;
        case 82: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 173: break;
        case 44: 
          { return symbol(ANDAND);
          }
        case 174: break;
        case 83: 
          { return symbol(WHILE);
          }
        case 175: break;
        case 31: 
          { throw new RuntimeException("Unterminated character literal at end of line");
          }
        case 176: break;
        case 70: 
          { return symbol(ELSE);
          }
        case 177: break;
        case 57: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character(yytext().charAt(0)));
          }
        case 178: break;
        case 18: 
          { return symbol(COMMA);
          }
        case 179: break;
        case 85: 
          { return symbol(RETURN);
          }
        case 180: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          scanner = new Scanner( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
