
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 22 21:20:09 CST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LONG_LITERAL = 63;
  public static final int DIV_EQ = 43;
  public static final int STRING_LITERAL = 61;
  public static final int GTEQ = 49;
  public static final int SHORT = 13;
  public static final int MULT = 35;
  public static final int CHAR = 3;
  public static final int LTEQ = 48;
  public static final int MINUS_MINUS = 39;
  public static final int CASE = 15;
  public static final int LPAREN = 44;
  public static final int CONTINUE = 16;
  public static final int INT = 5;
  public static final int FOR = 19;
  public static final int MINUS = 34;
  public static final int WRITE = 22;
  public static final int RPAREN = 45;
  public static final int BOOLEAN_LITERAL = 59;
  public static final int OROR = 53;
  public static final int CHARACTER_LITERAL = 60;
  public static final int NOT = 30;
  public static final int SEMICOLON = 27;
  public static final int LT = 55;
  public static final int OCT_LITERAL = 65;
  public static final int MULT_EQ = 42;
  public static final int COMMA = 28;
  public static final int HEX_LITERAL = 64;
  public static final int ANDAND = 51;
  public static final int DIV = 36;
  public static final int SHORT_LITERAL = 62;
  public static final int PLUS = 33;
  public static final int NULL_LITERAL = 66;
  public static final int IF = 6;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int PLUS_PLUS = 38;
  public static final int RETURN = 8;
  public static final int error = 1;
  public static final int EQEQ = 47;
  public static final int MOD = 37;
  public static final int BREAK = 14;
  public static final int VOID = 9;
  public static final int EQ = 46;
  public static final int SWITCH = 20;
  public static final int LBRACK = 25;
  public static final int COLON = 32;
  public static final int FLOATING_POINT_LITERAL = 58;
  public static final int LBRACE = 23;
  public static final int ELSE = 4;
  public static final int READ = 21;
  public static final int RBRACK = 26;
  public static final int WHILE = 10;
  public static final int DEFAULT = 17;
  public static final int FLOAT = 11;
  public static final int PUBLIC = 7;
  public static final int RBRACE = 24;
  public static final int LONG = 12;
  public static final int QUESTION = 31;
  public static final int PLUS_EQ = 40;
  public static final int MINUS_EQ = 41;
  public static final int AT = 52;
  public static final int GT = 54;
  public static final int DO = 18;
  public static final int NOTEQ = 50;
  public static final int INTEGER_LITERAL = 57;
  public static final int IDENTIFIER = 56;
}

